
--Basic CRUD Operations (create)
CREATE TABLE Customer (
    Customer_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Customer_Name VARCHAR2(70) NOT NULL,
    Customer_DOB DATE,
    Gender CHAR(1),--male or female
    Email VARCHAR2(100) NOT NULL,
    Phone_No VARCHAR2(15) NOT NULL
);


CREATE TABLE Reservation_Type (
    Reservation_Type_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Reservation_Type_Name VARCHAR2(50) NOT NULL
);


CREATE TABLE Department (
    Dep_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Department_Name VARCHAR2(100) NOT NULL,
    Work_Location VARCHAR2(200) NOT NULL,
    Maneger_Id NUMBER
);


CREATE TABLE Movies (
    Movie_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Movie_Name VARCHAR2(100) NOT NULL,
    Movie_Type VARCHAR2(50),
    Language_of_movie VARCHAR2(50),
    Rating NUMBER(3, 1),
    Description_for_movie VARCHAR2(500)
);


CREATE TABLE Employee (
    Employee_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Employee_Name VARCHAR2(100) NOT NULL,
    Salary NUMBER(6, 2) NOT NULL,
    Employee_DOB DATE,
    Hire_Date DATE NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    Phone_No VARCHAR2(15) NOT NULL,
    Address_of_Employee VARCHAR2(200) NOT NULL,
    Dep_ID NUMBER,
    CONSTRAINT fk_employee_department FOREIGN KEY (Dep_ID) REFERENCES Department(Dep_ID)
);


CREATE TABLE Online_Account (
    Account_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Customer_ID NUMBER NOT NULL,
    Username VARCHAR2(50) NOT NULL,
    Passwords VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_online_account_customer FOREIGN KEY (Customer_ID) REFERENCES Customer(Customer_ID)
);


CREATE TABLE Hall (
    Hall_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Hall_Name VARCHAR2(100) NOT NULL,
    Capacity NUMBER NOT NULL,
    Hall_Type VARCHAR2(50) NOT NULL,
    Dep_ID NUMBER,
    CONSTRAINT fk_hall_department FOREIGN KEY (Dep_ID) REFERENCES Department(Dep_ID)
);


CREATE TABLE Showtimes (
    Showtime_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Movie_ID NUMBER NOT NULL,
    Hall_ID NUMBER NOT NULL,
    Show_Date DATE NOT NULL,
    CONSTRAINT fk_showtimes_movie FOREIGN KEY (Movie_ID) REFERENCES Movies(Movie_ID),
    CONSTRAINT fk_showtimes_hall FOREIGN KEY (Hall_ID) REFERENCES Hall(Hall_ID)
);



CREATE TABLE Seat (
    Seat_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Hall_ID NUMBER NOT NULL,
    Row_num VARCHAR2(10) NOT NULL,
    Seat_Number NUMBER NOT NULL,
    CONSTRAINT fk_seat_hall FOREIGN KEY (Hall_ID) REFERENCES Hall(Hall_ID)
);



CREATE TABLE Ticket (
    Ticket_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Showtime_ID NUMBER NOT NULL,
    Seat_ID NUMBER NOT NULL,
    Ticket_Type VARCHAR2(50) NOT NULL,
    Price NUMBER(6, 2) NOT NULL,
    CONSTRAINT fk_ticket_showtime FOREIGN KEY (Showtime_ID) REFERENCES Showtimes(Showtime_ID),
    CONSTRAINT fk_ticket_seat FOREIGN KEY (Seat_ID) REFERENCES Seat(Seat_ID)
);


CREATE TABLE Reservation (
    Reservation_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Customer_ID NUMBER NOT NULL,
    Reservation_Type_ID NUMBER NOT NULL,
    Reservation_Date DATE NOT NULL,
    CONSTRAINT fk_reservation_customer FOREIGN KEY (Customer_ID) REFERENCES Customer(Customer_ID),
    CONSTRAINT fk_reservation_type FOREIGN KEY (Reservation_Type_ID) REFERENCES Reservation_Type(Reservation_Type_ID)
);



CREATE TABLE Reservation_Ticket (
    Reservation_ID NUMBER NOT NULL,
    Ticket_ID NUMBER NOT NULL,
    PRIMARY KEY (Reservation_ID, Ticket_ID),
    CONSTRAINT fk_reservation_ticket_reservation FOREIGN KEY (Reservation_ID) REFERENCES Reservation(Reservation_ID),
    CONSTRAINT fk_reservation_ticket_ticket FOREIGN KEY (Ticket_ID) REFERENCES Ticket(Ticket_ID)
);


CREATE TABLE Payments (
    Payment_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ticket_ID NUMBER NOT NULL,
    Payment_Date DATE NOT NULL,
    Amount NUMBER(6, 2) NOT NULL,
    Payment_Method VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_payments_ticket FOREIGN KEY (Ticket_ID) REFERENCES Ticket(Ticket_ID)
);


CREATE TABLE Snacks (
    Snack_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Snack_Name VARCHAR2(100) NOT NULL,
    Snack_Category VARCHAR2(50) NOT NULL,
    Snack_Price NUMBER(6, 2) NOT NULL,
    Dep_ID NUMBER,
    CONSTRAINT fk_snacks_department FOREIGN KEY (Dep_ID) REFERENCES Department(Dep_ID)
);



